import { NextResponse } from "next/server";
import { buildDiffItemsFromAnalysis, buildOptimizedMarkdown } from "@/lib/cv-template-renderer";

export const maxDuration = 60;

export async function GET() {
  return NextResponse.json({ cv_versions: [] });
}

export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const analysis = body.source_context?.analysis ?? body.analysis ?? {};
    const role = analysis.role || body.target_role || "CV toi uu";
    const id = `local_cv_${Date.now()}`;
    const diffItems = buildDiffItemsFromAnalysis(analysis);

    return NextResponse.json({
      ok: true,
      cv_version_id: id,
      id,
      title: `${role} - CV toi uu`,
      target_role: role,
      status: "ready",
      created_at: new Date().toISOString(),
      diff_count: diffItems.length,
      diff_items: diffItems,
      optimized_markdown: buildOptimizedMarkdown({ analysis }),
      note: "Generated by Next.js local fallback.",
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ detail: message }, { status: 500 });
  }
}
